//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("Cake.Topshelf")]
[assembly: AssemblyVersion("0.0.8")]
[assembly: AssemblyFileVersion("0.0.8")]
[assembly: AssemblyInformationalVersion("0.0.8")]
[assembly: AssemblyCopyright("Copyright (c) 2015 - 2017 Sergio Silveira, Phillip Sharpe")]

